# Generated by Django 3.0.7 on 2020-07-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.ArtCategory'),
        ),
        migrations.AlterField(
            model_name='consumerism',
            name='shop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='culturallife',
            name='events',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='popularculture',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='urbanism',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
