# Generated by Django 3.0.7 on 2020-07-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200712_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Person'),
        ),
    ]
