# Generated by Django 3.0.7 on 2020-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200622_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='SocialIssues',
            new_name='SocialIssue',
        ),
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name_plural': 'Biographies'},
        ),
        migrations.AlterModelOptions(
            name='consumerism',
            options={'verbose_name_plural': 'Consumerism'},
        ),
        migrations.AlterModelOptions(
            name='culturallife',
            options={'verbose_name_plural': 'Cultural Lives'},
        ),
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name_plural': 'Literature'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='objectsmentioned',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='politics',
            options={'verbose_name_plural': 'Politics'},
        ),
        migrations.AlterModelOptions(
            name='psychology',
            options={'verbose_name_plural': 'Psychologies'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='social_issues',
            new_name='social_issue',
        ),
    ]
