# Generated by Django 3.0.7 on 2020-07-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200714_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.ArtCategory'),
        ),
    ]
