# Generated by Django 3.0.7 on 2020-07-16 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200715_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_of_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.TypeOfFormat'),
        ),
    ]
