# Generated by Django 3.0.7 on 2020-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200625_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
