# Generated by Django 3.0.7 on 2020-07-16 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_article_type_of_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicsperiod',
            name='years',
        ),
        migrations.AddField(
            model_name='politicsperiod',
            name='end_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AddField(
            model_name='politicsperiod',
            name='start_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
