# Generated by Django 3.0.7 on 2020-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200626_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('RR', 'Ready for Review'), ('R', 'Reviewed')], default='I', max_length=2),
        ),
        migrations.AlterField(
            model_name='consumerism',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
