# Generated by Django 3.0.7 on 2020-07-16 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20200716_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='start_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='politicsperiod',
            name='end_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='politicsperiod',
            name='start_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1600), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
