# Generated by Django 3.0.7 on 2020-07-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20200716_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.ManyToManyField(to='forms.Occupation'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='relation',
        ),
        migrations.AddField(
            model_name='person',
            name='relation',
            field=models.ManyToManyField(to='forms.Relation'),
        ),
    ]
