# Generated by Django 3.0.7 on 2020-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20200716_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperiod',
            name='end_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperiod',
            name='start_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politicsperiod',
            name='end_year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politicsperiod',
            name='start_year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
