# Generated by Django 3.0.7 on 2020-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20200723_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='place_of_publication',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
