# Generated by Django 3.0.7 on 2020-07-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_article_place_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoftext',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.TypeOfFormat'),
        ),
    ]
