# Generated by Django 3.0.7 on 2020-07-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20200730_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.ArtCategory'),
        ),
    ]
