# Generated by Django 3.0.7 on 2020-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20200801_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='coordinates',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='coordinates',
            new_name='geom',
        ),
    ]
