from django.contrib import admin
from forms.models import *

admin.site.site_url = 'https://pg72.host.cs.st-andrews.ac.uk/ramon/forms/articles'

# Register your models here.
admin.site.register(LocationType)
admin.site.register(Location)
admin.site.register(BuildingType)
admin.site.register(Building)
admin.site.register(ArtType)
admin.site.register(Artist)
admin.site.register(ArtStyle)
admin.site.register(ArtisticMovement)
admin.site.register(Art)
admin.site.register(AppliedArt)
admin.site.register(FormatOfText)
admin.site.register(PoliticsPeriod)
admin.site.register(Politics)
admin.site.register(Relation)
admin.site.register(Period)
admin.site.register(Biography)
admin.site.register(Urbanism)
admin.site.register(Architecture)
admin.site.register(CulturalLife)
admin.site.register(Movement)
admin.site.register(Writer)
admin.site.register(Literature)
admin.site.register(CultureType)
admin.site.register(PopularCulture)
admin.site.register(Entertainment)
admin.site.register(MediaType)
admin.site.register(Media)
admin.site.register(ObjectsMentioned)
admin.site.register(Psychology)
admin.site.register(SocialIssue)
admin.site.register(SocialScience)
admin.site.register(ConsumerismType)
admin.site.register(Consumerism)
admin.site.register(Article)
