from django.contrib import admin
from forms.models import *

admin.site.site_url = 'https://pg72.host.cs.st-andrews.ac.uk/ramon/forms/articles'

# Register your models here.
admin.site.register(Article)
admin.site.register(Occupation)
admin.site.register(Relation)
admin.site.register(Person)
admin.site.register(LocationType)
admin.site.register(Location)
admin.site.register(BuildingType)
admin.site.register(Building)
admin.site.register(TypeOfFormat)
admin.site.register(FormatOfText)
admin.site.register(PersonalMemory)
admin.site.register(HistoricalPeriod)
admin.site.register(HistoricalMemory)
admin.site.register(PoliticsPeriod)
admin.site.register(Politics)
admin.site.register(Architecture)
admin.site.register(Urbanism)
admin.site.register(ArtCategory)
admin.site.register(ArtType)
admin.site.register(ArtStyle)
admin.site.register(ArtisticMovement)
admin.site.register(Art)
admin.site.register(CulturalLife)
admin.site.register(AestheticMovement)
admin.site.register(Aesthetic)
admin.site.register(LiteraryMovement)
admin.site.register(LiteraryGenre)
admin.site.register(Literature)
admin.site.register(PopularCulture)
admin.site.register(Entertainment)
admin.site.register(MediaType)
admin.site.register(Media)
admin.site.register(LeisureType)
admin.site.register(Leisure)
admin.site.register(Fashion)
admin.site.register(Consumerism)
admin.site.register(TypeOfScience)
admin.site.register(Science)
admin.site.register(ObjectsMentioned)
