"""ramon URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from forms import views

urlpatterns = [
    # url(r'^$', views.Index.as_view(), name='home'),
    url(r'^articles$', views.Articles.as_view(), name='home'),
    url(r'^locations$', views.Locations.as_view(), name='locations'),
    url(r'^location-types$', views.LocationTypes.as_view(), name='location-types'),
    url(r'^buildings$', views.Buildings.as_view(), name='buildings'),
    url(r'^building-types$', views.BuildingTypes.as_view(), name='building-types'),
    url(r'^arts$', views.Arts.as_view(), name='arts'),
    url(r'^art-types$', views.ArtTypes.as_view(), name='art-types'),
    url(r'^artist-types$', views.ArtistTypes.as_view(), name='artist-types'),
    url(r'^artists$', views.Artists.as_view(), name='artists'),
    url(r'^art-styles$', views.ArtStyles.as_view(), name='art-styles'),
    url(r'^artistic-movements$', views.ArtisticMovements.as_view(), name='artistic-movements'),
    url(r'^applied-arts$', views.AppliedArts.as_view(), name='applied-arts'),
    url(r'^text-formats$', views.FormatOfTexts.as_view(), name='text-formats'),
    url(r'^politics$', views.Politics.as_view(), name='politics'),
    url(r'^politics-periods$', views.PoliticsPeriod.as_view(), name='politics-periods'),
    url(r'^biographies$', views.Biographies.as_view(), name='biographies'),
    url(r'^relations$', views.Relations.as_view(), name='relations'),
    url(r'^biography-periods$', views.BiographyPeriod.as_view(), name='biography-periods'),
    url(r'^urbanism$', views.Urbanism.as_view(), name='urbanism'),
    url(r'^architectures$', views.Architectures.as_view(), name='architectures'),
    url(r'^cultural-life$', views.CulturalLife.as_view(), name='cultural-life'),
    url(r'^literature$', views.Literature.as_view(), name='literature'),
    url(r'^movements$', views.Movements.as_view(), name='movements'),
    url(r'^writers$', views.Writers.as_view(), name='writers'),
    url(r'^popular-cultures$', views.PopularCultures.as_view(), name='popular-cultures'),
    url(r'^culture-types$', views.CultureTypes.as_view(), name='culture-types'),
    url(r'^entertainment$', views.Entertainment.as_view(), name='entertainment'),
    url(r'^media$', views.Media.as_view(), name='media'),
    url(r'^media-types$', views.MediaTypes.as_view(), name='media-types'),
    url(r'^objects$', views.Objects.as_view(), name='objects'),
    url(r'^psychology$', views.Psychology.as_view(), name='psychology'),
    url(r'^social-issues$', views.SocialIssues.as_view(), name='social-issues'),
    url(r'^social-science$', views.SocialScience.as_view(), name='social-science'),
    url(r'^consumerism$', views.Consumerism.as_view(), name='consumerism'),
    url(r'^consumerism-types$', views.ConsumerismTypes.as_view(), name='consumerism-types'),

    url(r'^new-locations(?:/(?P<id>[0-9]+))?/$', views.NewLocations.as_view(), name='new-locations'),
    url(r'^new-location-types/$', views.NewLocationType.as_view(), name='new-location-types'),
    url(r'^new-buildings(?:/(?P<id>[0-9]+))?/$', views.NewBuildings.as_view(), name='new-buildings'),
    url(r'^new-building-types/$', views.NewBuildingType.as_view(), name='new-building-types'),
    url(r'^new-arts/$', views.NewArts.as_view(), name='new-arts'),
    url(r'^new-art-types/$', views.NewArtTypes.as_view(), name='new-art-types'),
    url(r'^new-artist-types/$', views.NewArtistTypes.as_view(), name='new-artist-types'),
    url(r'^new-artists/$', views.NewArtists.as_view(), name='new-artists'),
    url(r'^new-art-styles/$', views.NewArtStyles.as_view(), name='new-art-styles'),
    url(r'^new-artistic-movements/$', views.NewArtisticMovements.as_view(), name='new-artistic-movements'),
    url(r'^new-applied-arts/$', views.NewAppliedArts.as_view(), name='new-applied-arts'),
    url(r'^new-text-formats/$', views.NewFormatOfTexts.as_view(), name='new-text-formats'),
    url(r'^new-politics-periods/$', views.NewPoliticsPeriod.as_view(), name='new-politics-periods'),
    url(r'^new-politics/$', views.NewPolitics.as_view(), name='new-politics'),
    url(r'^new-relations/$', views.NewRelations.as_view(), name='new-relations'),
    url(r'^new-biography-periods/$', views.NewBiographyPeriod.as_view(), name='new-biography-periods'),
    url(r'^new-biographies/$', views.NewBiographies.as_view(), name='new-biographies'),
    url(r'^new-urbanism/$', views.NewUrbanism.as_view(), name='new-urbanism'),
    url(r'^new-architectures/$', views.NewArchitectures.as_view(), name='new-architectures'),
    url(r'^new-cultural-life/$', views.NewCulturalLife.as_view(), name='new-cultural-life'),
    url(r'^new-movements/$', views.NewMovements.as_view(), name='new-movements'),
    url(r'^new-writers/$', views.NewWriters.as_view(), name='new-writers'),
    url(r'^new-literature/$', views.NewLiterature.as_view(), name='new-literature'),
    url(r'^new-culture-types/$', views.NewCultureTypes.as_view(), name='new-culture-types'),
    url(r'^new-popular-cultures/$', views.NewPopularCultures.as_view(), name='new-popular-cultures'),
    url(r'^new-entertainment/$', views.NewEntertainment.as_view(), name='new-entertainment'),
    url(r'^new-media-types/$', views.NewMediaTypes.as_view(), name='new-media-types'),
    url(r'^new-media/$', views.NewMedia.as_view(), name='new-media'),
    url(r'^new-objects/$', views.NewObjects.as_view(), name='new-objects'),
    url(r'^new-psychology/$', views.NewPsychology.as_view(), name='new-psychology'),
    url(r'^new-social-issues/$', views.NewSocialIssues.as_view(), name='new-social-issues'),
    url(r'^new-social-science/$', views.NewSocialScience.as_view(), name='new-social-science'),
    url(r'^new-consumerism-types/$', views.NewConsumerismTypes.as_view(), name='new-consumerism-types'),
    url(r'^new-consumerism/$', views.NewConsumerism.as_view(), name='new-consumerism'),
    url(r'^new-articles/$', views.NewArticles.as_view(), name='new-articles'),

    url(r'^(?P<pk>\d+)/edit-location-types/$', views.EditLocationType.as_view(), name='edit-location-types'),
    url(r'^(?P<pk>\d+)/edit-building-types/$', views.EditBuildingType.as_view(), name='edit-building-types'),
    url(r'^(?P<pk>\d+)/edit-arts/$', views.EditArts.as_view(), name='edit-arts'),
    url(r'^(?P<pk>\d+)/edit-art-types/$', views.EditArtTypes.as_view(), name='edit-art-types'),
    url(r'^(?P<pk>\d+)/edit-artist-types/$', views.EditArtistTypes.as_view(), name='edit-artist-types'),
    url(r'^(?P<pk>\d+)/edit-artists/$', views.EditArtists.as_view(), name='edit-artists'),
    url(r'^(?P<pk>\d+)/edit-art-styles/$', views.EditArtStyles.as_view(), name='edit-art-styles'),
    url(r'^(?P<pk>\d+)/edit-artistic-movements/$', views.EditArtisticMovements.as_view(), name='edit-artistic-movements'),
    url(r'^(?P<pk>\d+)/edit-applied-arts/$', views.EditAppliedArts.as_view(), name='edit-applied-arts'),
    url(r'^(?P<pk>\d+)/edit-text-formats/$', views.EditFormatOfTexts.as_view(), name='edit-text-formats'),
    url(r'^(?P<pk>\d+)/edit-politics-periods/$', views.EditPoliticsPeriod.as_view(), name='edit-politics-periods'),
    url(r'^(?P<pk>\d+)/edit-politics/$', views.EditPolitics.as_view(), name='edit-politics'),
    url(r'^(?P<pk>\d+)/edit-relations/$', views.EditRelations.as_view(), name='edit-relations'),
    url(r'^(?P<pk>\d+)/edit-biography-periods/$', views.EditBiographyPeriod.as_view(), name='edit-biography-periods'),
    url(r'^(?P<pk>\d+)/edit-biographies/$', views.EditBiographies.as_view(), name='edit-biographies'),
    url(r'^(?P<pk>\d+)/edit-urbanism/$', views.EditUrbanism.as_view(), name='edit-urbanism'),
    url(r'^(?P<pk>\d+)/edit-architectures/$', views.EditArchitectures.as_view(), name='edit-architectures'),
    url(r'^(?P<pk>\d+)/edit-cultural-life/$', views.EditCulturalLife.as_view(), name='edit-cultural-life'),
    url(r'^(?P<pk>\d+)/edit-movements/$', views.EditMovements.as_view(), name='edit-movements'),
    url(r'^(?P<pk>\d+)/edit-writers/$', views.EditWriters.as_view(), name='edit-writers'),
    url(r'^(?P<pk>\d+)/edit-literature/$', views.EditLiterature.as_view(), name='edit-literature'),
    url(r'^(?P<pk>\d+)/edit-culture-types/$', views.EditCultureTypes.as_view(), name='edit-culture-types'),
    url(r'^(?P<pk>\d+)/edit-popular-cultures/$', views.EditPopularCultures.as_view(), name='edit-popular-cultures'),
    url(r'^(?P<pk>\d+)/edit-entertainment/$', views.EditEntertainment.as_view(), name='edit-entertainment'),
    url(r'^(?P<pk>\d+)/edit-media-types/$', views.EditMediaTypes.as_view(), name='edit-media-types'),
    url(r'^(?P<pk>\d+)/edit-media/$', views.EditMedia.as_view(), name='edit-media'),
    url(r'^(?P<pk>\d+)/edit-objects/$', views.EditObjects.as_view(), name='edit-objects'),
    url(r'^(?P<pk>\d+)/edit-psychology/$', views.EditPsychology.as_view(), name='edit-psychology'),
    url(r'^(?P<pk>\d+)/edit-social-issues/$', views.EditSocialIssues.as_view(), name='edit-social-issues'),
    url(r'^(?P<pk>\d+)/edit-social-science/$', views.EditSocialScience.as_view(), name='edit-social-science'),
    url(r'^(?P<pk>\d+)/edit-consumerism-types/$', views.EditConsumerismTypes.as_view(), name='edit-consumerism-types'),
    url(r'^(?P<pk>\d+)/edit-consumerism/$', views.EditConsumerism.as_view(), name='edit-consumerism'),
    url(r'^(?P<pk>\d+)/edit-articles/$', views.EditArticles.as_view(), name='edit-articles'),

    url(r'^delete-location/(?P<id>[0-9]+)$', views.DeleteLocation.as_view(), name='delete-location'),
    url(r'^delete-location-types/(?P<id>[0-9]+)$', views.DeleteLocationTypes.as_view(), name='delete-location-types'),
    url(r'^delete-buildings/(?P<id>[0-9]+)$', views.DeleteBuildings.as_view(), name='delete-buildings'),
    url(r'^delete-building-types/(?P<id>[0-9]+)$', views.DeleteBuildingTypes.as_view(), name='delete-building-types'),
    url(r'^delete-arts/(?P<id>[0-9]+)$', views.DeleteArts.as_view(), name='delete-arts'),
    url(r'^delete-art-types/(?P<id>[0-9]+)$', views.DeleteArtTypes.as_view(), name='delete-art-types'),
    url(r'^delete-artist-types/(?P<id>[0-9]+)$', views.DeleteArtistTypes.as_view(), name='delete-artist-types'),
    url(r'^delete-artists/(?P<id>[0-9]+)$', views.DeleteArtist.as_view(), name='delete-artists'),
    url(r'^delete-art-styles/(?P<id>[0-9]+)$', views.DeleteArtStyles.as_view(), name='delete-art-styles'),
    url(r'^delete-artistic-movements/(?P<id>[0-9]+)$', views.DeleteArtisticMovements.as_view(), name='delete-artistic-movements'),
    url(r'^delete-applied-arts/(?P<id>[0-9]+)$', views.DeleteAppliedArts.as_view(), name='delete-applied-arts'),
    url(r'^delete-text-formats/(?P<id>[0-9]+)$', views.DeleteFormatOfTexts.as_view(), name='delete-text-formats'),
    url(r'^delete-politics-periods/(?P<id>[0-9]+)$', views.DeletePoliticsPeriod.as_view(), name='delete-politics-periods'),
    url(r'^delete-politics/(?P<id>[0-9]+)$', views.DeletePolitics.as_view(), name='delete-politics'),
    url(r'^delete-relations/(?P<id>[0-9]+)$', views.DeleteRelations.as_view(), name='delete-relations'),
    url(r'^delete-biography-periods/(?P<id>[0-9]+)$', views.DeleteBiographyPeriod.as_view(), name='delete-biography-periods'),
    url(r'^delete-biographies/(?P<id>[0-9]+)$', views.DeleteBiographies.as_view(), name='delete-biographies'),
    url(r'^delete-urbanism/(?P<id>[0-9]+)$', views.DeleteUrbanism.as_view(), name='delete-urbanism'),
    url(r'^delete-architectures/(?P<id>[0-9]+)$', views.DeleteArchitectures.as_view(), name='delete-architectures'),
    url(r'^delete-cultural-life/(?P<id>[0-9]+)$', views.DeleteCulturalLife.as_view(), name='delete-cultural-life'),
    url(r'^delete-movements/(?P<id>[0-9]+)$', views.DeleteMovements.as_view(), name='delete-movements'),
    url(r'^delete-writers/(?P<id>[0-9]+)$', views.DeleteWriters.as_view(), name='delete-writers'),
    url(r'^delete-literature/(?P<id>[0-9]+)$', views.DeleteLiterature.as_view(), name='delete-literature'),
    url(r'^delete-culture-types/(?P<id>[0-9]+)$', views.DeleteCultureTypes.as_view(), name='delete-culture-types'),
    url(r'^delete-popular-cultures/(?P<id>[0-9]+)$', views.DeletePopularCultures.as_view(), name='delete-popular-cultures'),
    url(r'^delete-entertainment/(?P<id>[0-9]+)$', views.DeleteEntertainment.as_view(), name='delete-entertainment'),
    url(r'^delete-media-types/(?P<id>[0-9]+)$', views.DeleteMediaTypes.as_view(), name='delete-media-types'),
    url(r'^delete-media/(?P<id>[0-9]+)$', views.DeleteMedia.as_view(), name='delete-media'),
    url(r'^delete-objects/(?P<id>[0-9]+)$', views.DeleteObjects.as_view(), name='delete-objects'),
    url(r'^delete-psychology/(?P<id>[0-9]+)$', views.DeletePsychology.as_view(), name='delete-psychology'),
    url(r'^delete-social-issues/(?P<id>[0-9]+)$', views.DeleteSocialIssues.as_view(), name='delete-social-issues'),
    url(r'^delete-social-science/(?P<id>[0-9]+)$', views.DeleteSocialScience.as_view(), name='delete-social-science'),
    url(r'^delete-consumerism-types/(?P<id>[0-9]+)$', views.DeleteConsumerismTypes.as_view(), name='delete-consumerism-types'),
    url(r'^delete-consumerism/(?P<id>[0-9]+)$', views.DeleteConsumerism.as_view(), name='delete-consumerism'),
    url(r'^delete-articles/(?P<id>[0-9]+)$', views.DeleteArticles.as_view(), name='delete-articles'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
